---
title: "2_26"
author: "Daniel Shapiro"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(rstanarm)
library(broom)
library(scales)
library(tidybayes)
```

```{r}
set.seed(9)

load("nes.rda")

nes <- nes %>%
  select(year, partyid7, real_ideo, race_adj, age_discrete, educ1, female, income) %>%
  drop_na() %>%
  mutate(gender = as.factor(ifelse(female == 1, "female", "non-female"))) %>%
  mutate(pred_ideology, )

reg_1 <- stan_glm(partyid7 ~ gender, data = nes, refresh = 0)
```

```{r}
set.seed(9)

summary(reg_1)

# How to interpret standard error (sigma): residual sd = Party ID will be within +/- 2.1 68% of the time.

tidy_coef <- tidy(reg_1)

model_intercept <- tidy_coef$estimate[1]
model_slope <- tidy_coef$estimate[2]

draws <- spread_draws(reg_1, `(Intercept)`, `gendernon-female`)

ggplot(nes, aes(x = gender, y = partyid7)) +
  geom_point() +
  geom_abline(data = draws, aes(intercept = `(Intercept)`, slope = `gendernon-female`), size = 0.1, alpha = 0.08, color = "skyblue") +
  geom_abline(intercept = model_intercept, slope = model_slope) +
  scale_y_continuous(labels = comma) +
  labs(title = "Relationship of Gender and Party ID Among Selected Voters",
       subtitle = "Data from Textbook",
       x = "Gender",
       y = "Party ID (1 is More Liberal, 7 is More Conservative)")
```

```{r}
# calculate est. for every value of data. Shoots back means for female and male. 

nes %>%
  select(partyid7, gender) %>%
  mutate(pred = predict(reg_1, nes))
```

```{r}
set.seed(9)

# Analyze connection between race and party id. Running stan_glm() doesn't make sense.

race <- nes %>%
  mutate(race = as.factor(case_when(race_adj == 1 ~ "white", 
                                    race_adj == 2 ~ "black", 
                                    race_adj == 1.5 ~ "other")))

race <- race %>%
  select(partyid7, race)

reg_2 <- stan_glm(partyid7 ~ race, data = race, refresh = 0)
summary(reg_2)
```

```{r}
fit_2 <- race %>%
  mutate(pred_1 = predict(reg_2, race))
```

